### ISSUE TITLE
Logo/Proposal

### ISSUE THREAD

**Issue by jbeguna04** [chayxana/Restaurant-App#10]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by jurabek** [comment]
sure, you can do that

**Comment by jbeguna04** [comment]
Ill be posting the designs here. Thank you for waiting !

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39085315-3a09499a-45b3-11e8-892e-08daf0c2d686.png)
![image](https://user-images.githubusercontent.com/35353768/39085323-5168467c-45b3-11e8-8538-25b7c1183e62.png)
![image](https://user-images.githubusercontent.com/35353768/39085367-d78f815c-45b3-11e8-80fd-7676e8e6b3a4.png)
![image](https://user-images.githubusercontent.com/35353768/39085400-36a95c76-45b4-11e8-8c93-5cc324a0e694.png)

**Comment by jurabek** [comment]
Hi @jbeguna04, looks awesome but the icons we should use on the first page on introduction page it is on the first screenshot, and if you want, try to change app colors which is more relevant to foods.

**Comment by jbeguna04** [comment]
Sure anything for this project sir, I loved to help those open source projects like this
Do you mean this one?
![image](https://user-images.githubusercontent.com/35353768/39184845-9936e684-47f7-11e8-9f0b-14ad5b71f0c0.png)

**Comment by jurabek** [comment]
yes

**Comment by jbeguna04** [comment]
Thank you for the quick reply, ill be posting the designs here later

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39186763-11c332d2-47fe-11e8-8c65-26354ccb770e.png)
![image](https://user-images.githubusercontent.com/35353768/39187003-a6bb0856-47fe-11e8-8ea2-7ff6d3f9949a.png)
![image](https://user-images.githubusercontent.com/35353768/39188125-95326c20-4801-11e8-985a-b307d1d5603c.png)

**Comment by jurabek** [comment]
Great job, 
could you, please upload those icons into the project to design folder, fork this repo and pull request me

**Comment by jbeguna04** [comment]
All of these 3 designs sir?

**Comment by jbeguna04** [comment]
I had already created a pull request, Hope you can see it, Thanks!

**Comment by jurabek** [comment]
@jbeguna04 to choosing color always was hard, I think orange and green is very suitable each other, I want to change all accent colors to green, on the last screenshot looks very very good.

**Comment by jbeguna04** [comment]
I had already made a PR for those 3 designs sir. Hope You can visit it https://github.com/Jurabek/Restaurant-App/pull/11

**Comment by jbeguna04** [comment]
Good evening sir, im so excited to see those designs in your project, please allow me to ask when will you use those designs ?

**Comment by jbeguna04** [comment]
Thank you again for accepting my designs, Feel free to approach me on your upcoming projects
