### ISSUE TITLE
Restaurant- backend

### ISSUE THREAD

**Issue by epeedoh** [chayxana/Restaurant-App#12]
Hello Jurabek Good Job. Being a beginner in dotnet core, I have problems trying to make the migration and generation of the database.
I have the errors:  

Unable to create an object of type 'DatabaseContext'. Add an implementation of 'IDesignTimeDbContextFactory<DatabaseContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
Thanck,

**Comment by Makaronii** [comment]
Hi, I will try to fix the bug :) I've had a very similar problem recently, and the reason was the error in EF: P

**Comment by jurabek** [comment]
Currently backend fully migrated to Docker and Microservices, there are should not be any problem with connection and Database Initialization
