### ISSUE TITLE
Unable to load Client solution

### ISSUE THREAD

**Issue by ali-h2010** [chayxana/Restaurant-App#16]
I am trying to open the client solution but i am getting an error:
Cannot load solution.
Load operation failed.

I am using Visual Studio for Mac build 7.7.4
For some reason, there is no log when i go to help -> Open Log Directory.

**Comment by jurabek** [comment]
@ali-h2010 fixed on the [f96140f0](https://github.com/Jurabek/Restaurant-App/commit/f96140f0aaf833fa13fffcd951fd89a67914613a)

**Comment by ali-h2010** [comment]
Many thanks for the quick response. 
I am not the most expert on Xamarin but I will try to contribute to this awesome project.
