### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by engmsaleh** [chayxana/Restaurant-App#30]
I'm getting this error when I'm trying to get it up `sudo docker-compose up`

```
Building menu-api
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

**Comment by jurabek** [comment]
@engmsaleh closing issue please check it out

**Comment by engmsaleh** [comment]
Now, I'm getting the following error 
```
cp: can't stat 'test/code_coverage.sh': No such file or directory
ERROR: Service 'menu-api' failed to build: The command '/bin/sh -c cp test/code_coverage.sh /apptest' returned a non-zero code: 1
```

**Comment by engmsaleh** [comment]
Solved the issue ... Thanks

**Comment by engmsaleh** [comment]
I have unrelated question, but how to access the running services .. 
I have deployed it on EC2 machine and want to access it from the web , Could you please advise?

**Comment by jurabek** [comment]
@engmsaleh I am not sure concerning `EC2` there are should be some way to run docker-compose but I would not recommend this way. 
The containers are deployable to `kubernetes clusters` you can use `AWS EKS` to deploy all containers and access it publically, currently this feature is in progress for this repository

**Comment by engmsaleh** [comment]
Ok, sounds good I have already a kubernetes cluster up .. Do you have any guide or advise about how to run it there? 
I have already converted the `docker-compose` into `deployments` and `services` using `kompose` and deployed them, but I didn't figure out how to access them from outside the cluster
