### ISSUE TITLE
class xyz is already defined in class R.Java (restaurant.droid)

### ISSUE THREAD

**Issue by jfnu** [chayxana/Restaurant-App#40]
I have been having issue in building restaurant,droid with 100 errors. All errors are similar to something like "Error:Class xyz is already defined in class R". 

I just pulled the latest and got this error. Do you know how to solve this issue? 

I'm new to xamarin but R.Java is a autogenerated class so I don't think I want to modify it.

Thank you

**Comment by jurabek** [comment]
It seems, it really depends on your setup, from your MonoDroid version, Visual Studio, Android Tools and etc...
yes, xamarin also generates like R.java file, it is Resources.Designer.cs file
so usually, what you can do, you can just remove Resource.Designer.cs from Restaurant.Android/Resources folder and see what happening...

**Comment by jfnu** [comment]
Thank you Jurabek.
that didn't solve it. I'm using VS 2019 and nothing else special. Downloaded the source in zip and opened it in VS and trying to compile it.
Do you have any other idea?
![image](https://user-images.githubusercontent.com/28159201/62873096-a098ca80-bcd3-11e9-89ae-ab92469d988d.png)

**Comment by jurabek** [comment]
Check it out here: https://stackoverflow.com/questions/18789857/xamarin-android-build-error-duplicate-class-r-java

**Comment by jfnu** [comment]
yeah tried that already and it didn't help. I take it that you don't experience this issue in your local? I wonder what could be wrong on my local then.  
But even I tried it on my fresh Mac OS machine with just VS for Mac installed, it also gave me same error message. 

Thank you for your help

**Comment by jurabek** [comment]
@jfnu I can reproduce the issue now on AppCenter, locally it is not reproducible, I will take a look it ASAP...

**Comment by jfnu** [comment]
great thank you so much

**Comment by jurabek** [comment]
It is broken on `Mono version 6.0.0.327` which is the latest version, I have no idea what is an issue, 
for the time being, you can downgrade it https://download.mono-project.com/archive/5.20.0/macos-10-universal/

**Comment by jurabek** [comment]
@jfnu fixed on the latest version

**Comment by jfnu** [comment]
Thank you...

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 22, 2019 at 2:32 AM, Jurabek<notifications@github.com> wrote:   
@jfnu fixed on the latest version
