### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by dhrn** [chayxana/Restaurant-App#56]
please add information about how to run the application.
(can we use existing CI scripts itself to run)

**Comment by jurabek** [comment]
Hi @dhrn 
go to the `cd src/Server/`
run `docker-compose up`
locally using Zuul reverse proxy you can call APIs using 
`http://localhost:8080/dashboard`,  `http://localhost:8080/menu/swagger/index.html`

CI scripts configured to the pipelines you can use it if you pass correct parameters

**Comment by dhrn** [comment]
Thanks. It will be good to have one section or separate file inside the project.

**Comment by jurabek** [comment]
outdated
