### ISSUE TITLE
What a coincidence!

### ISSUE THREAD

**Issue by jd-alexander** [chayxana/Restaurant-App#6]
Greetings, 
I am the developer of the Like Button library you included in the Xamarin Android project. I am sharpening my Xamarin Forms skills and I have been using your code as a guide for the past few days. I was so surprised when I saw the Twitter Like Button renderer and realized it was using my library haha. It's amazing how this platform allows us to help each other in ways we don't even know. Open source rocks!

**Comment by jurabek** [comment]
Yes, you are absolutely correct I created a binding library for https://github.com/jd-alexander/LikeButton, thank you for an amazing library. I am going to create binding lib for ios version https://github.com/xhamr/fave-button soon and then I will include this project informations and licences into my project.
