### ISSUE TITLE
Docker-compose basket-api

### ISSUE THREAD

**Issue by yurii1exe** [chayxana/Restaurant-App#85]
=> ERROR [restaurant/basket builder 8/8] RUN CGO_ENABLED=0 go test -c ./controllers -o controllers.test -cover
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/32770315/150399531-cab6d191-b4a2-431b-8a66-054ce1495db3.png">

**Comment by jurabek** [comment]
fixed on #86
